#!/usr/bin/env bash
# Configure your Nginx server sot that /redirect_me is redirecting ot another page 
sudo sed -i 's/^}/    rewrite \^\/redirect_me http:\/\/youtube.com\/watch\?v=QH2-TGULwu4 permanent;\n}/' /etc/nginx/sites-enabled/default
sudo service nginx restart
