#!/usr/bin/env bash
# Configure your Nginx server sot that /redirect_me is redirecting ot another page
sudo apt update
sudo apt install -y haproxy=2.0.\*

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend haproxy-main
        bind *:80
        option forwardfor
        default_backend web-backend

backend web-backend
        balance roundrobin
        server websvr1 44.200.63.37:80 check
        server websvr2 18.206.15.67:80 check
EOT
sudo service haproxy restart
