#!/usr/bin/env bash
# Configure your Nginx server sot that /redirect_me is redirecting ot another page
sudo apt update
sudo apt install -y haproxy=2.0.\*
sudo sed -i 's/^defaults$/defaults\n\t\tno option http-use-htx/' /etc/haproxy/haproxy.cfg

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend haproxy-main
        bind *:80
        option forwardfor
        default_backend web-backend

backend web-backend
        balance roundrobin
        server websvr1 107.23.209.127:80 check
        server websvr2 54.237.42.222:80 check
EOT
sudo service haproxy restart
