#!/usr/bin/env bash
# This scripts displays "Best School" 10 times but Hi on 9th iteration

n=1
while [[ $n -le 10 ]] 
do
	if [[ $n -eq 9 ]]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	n=$((n + 1))
done
