#!/usr/bin/env bash
# This script gives you information about the `school` file

filename="school"
if [[ -e "$filename" ]]; then
	echo "$filename file file exists"
	if [[ -s "$filename" ]]; then
		echo "$filename file is not empty"
	else
		echo "$filename file is empty"
	fi

	if [[ -f "$filename" ]]; then
		echo "$filename is a regular file"
	fi
else
	echo "$filename file does not exist"
fi
